# Generated by Django 4.1.7 on 2023-04-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True, unique=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('date_of_birth', models.CharField(help_text='Date format: <em>DD-MM-YYYY</em>.', max_length=10, null=True, verbose_name='DoB')),
                ('industry', models.CharField(max_length=50, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('years_of_experience', models.IntegerField(null=True, verbose_name='YoE')),
            ],
            options={
                'verbose_name_plural': 'employee',
                'ordering': ['first_name', 'last_name', 'industry'],
            },
        ),
    ]
