# Generated by Django 4.1.7 on 2023-04-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='years_of_experience',
            field=models.IntegerField(null=True, verbose_name='Yeor of experience'),
        ),
    ]
