# Generated by Django 4.1.7 on 2023-04-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_employee_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(help_text='Date format: <em>DD-MM-YYYY</em>.', max_length=10, null=True, verbose_name='DoB'),
        ),
    ]
