# Generated by Django 4.1.7 on 2023-04-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_employee_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(help_text='Date format: <em>DD-MM-YYYY</em>.', null=True, verbose_name='DoB'),
        ),
    ]
