# Generated by Django 4.1.7 on 2023-04-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(help_text='Date format: <em>DD/MM/YYYY</em>.', null=True, verbose_name='DoB'),
        ),
    ]
