# Generated by Django 4.1.7 on 2023-04-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_alter_employee_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='years_of_experience',
            field=models.IntegerField(null=True, verbose_name='Year of experience'),
        ),
    ]
